### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by dstehle** [dstehle/fplll#67]
(reported by Sylvain Chevillard and Christoph Lauter) 

The leak is described here;
https://gforge.inria.fr/tracker/?func=detail&group_id=1015&atid=4076&aid=20305

It may be that the static variable temp in nr_Z.inl is used as temporary variable by util.cpp. 
It seems the variable is never freed from memory with a call to mpfr_clear.

**Comment by shi-bai** [comment]
I just tested sollya linked with the current fplll version. It seems that the leaking is gone. I close this ticket for now. 

The following is a summary: there could be two problems (on my desktop&laptop).

-- mpfr_free_cache() needs to be called; otherwise it seems the valgrind will complain;
-- temp inside nr_Z.inl of LDConvHelper needs to be cleaned. Note it is a classic member. Thus we need to clean in the end of the function where it had been called. In particular, it is placed inside the deconstructor of class LLLReduction of lll.h
